#!/bin/zsh
echo Updating or installing homebrew...
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

echo Updating or installing imagemagick...
brew install imagemagick

echo Updating or installing node...
brew install node

echo Updating or installing phantomJS...
brew install phantomjs

echo Installing browserify...
npm install -g browserify

echo Installing R and the webshot package...
brew install r
Rscript installPkgs.R "webshot"